name: goal_details
description: A flutter application to collect goal details from the user.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.3.1
  path_provider: ^1.6.11
  hive: ^1.4.2
  hive_flutter: ^0.3.1
  json_annotation: ^3.0.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^3.2.0
  hive_generator: ^0.7.1
  cupertino_icons: ^0.1.3
  line_awesome_flutter: ^1.0.1
  google_fonts: ^1.1.0
  expandable: ^4.1.4

# An attempted workaround from issue https://github.com/flutter/flutter/issues/62240
# for https://github.com/simolus3/moor/issues/553 like build_runner runs indefinitely in flutter:v1.20.0.
dependency_overrides:
  analyzer: '0.39.14'

flutter:
  uses-material-design: true
  assets:
    - assets/background.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
